run:
  timeout: 30m
  tests: true
output:
  format: colored-line-number
  print-issued-lines: true
linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - exhaustive # Buggy
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - godot
    - godox
    - gofumpt
    - interfacebloat
    - interfacer
    - ireturn
    - nlreturn
    - nonamedreturns
    - varnamelen
    - wsl
linter-settings:
  nlreturn:
    blocksize: 2
  revive:
    - name: var-naming
      arguments:
        - ["Lhs", "Rhs", "Eof"]
        - []