run:
  timeout: 30m
  tests: true
output:
  format: colored-line-number
  print-issued-lines: true
linters-settings:
  gomnd:
    ignored-files:
      - 'ast/limits\.go$'
linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - exhaustive # Buggy
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - godot
    - godox
    - gofumpt
    - interfacebloat
    - interfacer
    - ireturn
    - nlreturn
    - nonamedreturns
    - varnamelen
    - wsl