name: go
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  go:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: go/go.sum
      - name: Install dependencies
        run: go mod tidy
        working-directory: go
      - name: Generate code
        run: go generate ./...
        working-directory: go
      - name: Compile
        run: go build -v ./...
        working-directory: go
      - name: Run tests
        run: go test -v ./...
        working-directory: go
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: "goinstall"
          version: v1.59
          working-directory: go
          args: --config="${GITHUB_WORKSPACE}/go/.golangci.yaml"
