name: golangci-lint
on:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: "goinstall"
          version: latest
          working-directory: go
          args: --config="${GITHUB_WORKSPACE}/go/.golangci.yaml"
