name: golangci-lint
on:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: go/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: "goinstall"
          version: v1.59
          working-directory: go
          args: --config="${GITHUB_WORKSPACE}/go/.golangci.yaml"
